### ISSUE TITLE
Documentation - specify that worker must import function in the same way as when it was inserted 

### ISSUE THREAD

**Issue by emjoyce** [seung-lab/python-task-queue#37]
It may be helpful someone in the future to specify that functions must be imported in the same way for the worker and for insertion (readme or a special error message). 

I had a function from a module of mine that I copied into a notebook to troubleshoot and edit. I added the queueable decorator right there in the notebook and used that function for my task insertion. I copied that edited function back into my module, and imported from there for the worker. 

I was getting the error 'not registered as a queueable function' and could not figure out what the issue was for a while. I had to import the function from my module for the insertion as well and then it worked.

**Comment by william-silversmith** [comment]
This is a great point. I'll add something to the README. I'm sure this has
been confusing many people who tried it but didn't post an issue.

**Comment by william-silversmith** [comment]
I wonder if it might be easier to just automatically import the functions. The data payload includes both the module and function to call, so that's something we could do. I'm just wondering if doing so would cause any security concerns.

**Comment by william-silversmith** [comment]
Yea, there would be. A compromised queue could then pull in functions that are not meant to be run. I'll stick with the warning.

**Comment by william-silversmith** [comment]
Thanks for opening the issue! Fixed.
