### ISSUE TITLE
How to multiprocessing the poll() operation?

### ISSUE THREAD

**Issue by JackieZhai** [seung-lab/python-task-queue#42]
Hi, @william-silversmith 

As for the "tq.poll()" operation of TaskQueue on the consumer side, is it possible for multiprocessing?
I just started multiple programs to achieve that as far as I know.
How about using ProcessPoolExecutor or something else?

Many thanks!

**Comment by william-silversmith** [comment]
Hi Jackie! 

If you use Igneous, it comes bundled with a parallel option, however if you're using this library raw the only built-in parallel option comes with the LocalTaskQueue which is all in-memory. It's something that could be added though. Starting multiple processes is the way Igneous is usually handled. We usually use a runner like kubernetes or SLURM to handle that part so it can be distributed across many machines.

**Comment by JackieZhai** [comment]
Wonderful advice!
I'll try as much as I can. :)
